### ISSUE TITLE
пишет не получилось найти контакт

### ISSUE THREAD

**Issue by Gripers** [LightninG8/telegram-spammer#1]

**Comment by LightninG8** [comment]
Привет! Не ожидал, что кто-то посмотрит мой код))
Если не получилось найти контакт - значит профиль не зарегистрирован в телеграме, либо просто профиль нельзя добавить по номеру телефона.

Я на питоне ничего не писал ранее, это мой первый опыт.

**Comment by LightninG8** [comment]
Я сделал релиз, где выложил инструкцию по пользованию программой
https://github.com/LightninG8/telegram-spammer/releases/tag/publish

**Comment by Gripers** [comment]
> Я сделал релиз, где выложил инструкцию по пользованию программой https://github.com/LightninG8/telegram-spammer/releases/tag/publish

Большое спасибо
